# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_command:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    
    - name: permission
      run: chmod -R +x ./main ./include ./Compiler
      shell: bash

    - name: build
      run: |
        ..\\Compiler\\bin\\make.exe
        ..\Compiler\bin\hex2000.exe $TARGET_BAT.out -o $TARGET_BAT.hex -map $TARGET_BAT.map -i -datawidth 16 -memwidth 16 -romwidth 16
        mkdir ..\build
        mv *.out *.map *.hex ..\build
      shell: bash
      working-directory: ~/main
      env:
        TARGET_BAT: a_hara

    - name: zip release files
      uses: actions/upload-artifact@v4
      with:
        name: c28x-build
        path: ./build

#    - name: build
#      run: ./build_Bat.bat
#      shell: bash
#      working-directory: ./main
#      #run: powershell.exe -Command " ./build_Bat.bat"
