# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_command:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    
    - name: permission
      run: chmod -R +x ./main ./include ./Compiler
      shell: bash

    - name: run
      run: ../Compiler/bin/make.exe
      shell: bash
      working-directory: ./main

    - name: build
      run: ./build_Bat.bat
      shell: bash
      working-directory: ./main
      #run: powershell.exe -Command " ./build_Bat.bat"
