# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_command:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: permission and cd
      run: |
        chmod -R +x .\main .\include .\Compiler
        cd main
    - name: run powershell and build
      run: |
        powershell.exe 
        $.\build_Bat.bat
      #run: powershell.exe -Command " .\build_Bat.bat"
