# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_command:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
    
    - name: permission
      run: chmod -R +x .\main .\include .\Compiler

    - name: run
      run: ..\Compiler\bin\make.exe
      working-directory: .\main

    - name: run powershell and build
      run: powershell .\build_Bat.bat
      working-directory: .\main
      #run: powershell.exe -Command " .\build_Bat.bat"
